CREATE TABLE IF NOT EXISTS inventory_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description VARCHAR(255),
    model_number VARCHAR(255),
    part_number VARCHAR(255),
    make VARCHAR(255),
    rack_number VARCHAR(255),
    quantity INTEGER,
    condition VARCHAR(255),
    location VARCHAR(255)
);